src/FirstDjangoProject22/FirstDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

src/FirstDjangoProject22/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('model/', views.getModelDetails, name='detail'),
    path('model/<int:model_detail_id>/result', views.getTrainingResult, name='trainingResult')
]

src/FirstDjangoProject22/polls/models.py
from django.db import models

# Create your models here.
class DelinquencyInputs(models.Model):
    variable_name = models.CharField(max_length=200)
    target_indicator = models.BooleanField()
    def __str__(self):
        return f'variable_name: {self.variable_name}, target_indicator: {self.target_indicator}'

class DelinquencyModel(models.Model):
    model_name = models.CharField(max_length=50)
    algorithm_used = models.CharField(max_length=100)
    def __str__(self):
        return f'model_name: {self.model_name}, algorithm_used: {self.algorithm_used}'

class ModelAttributes(models.Model):
    delinquency_model = models.ForeignKey(DelinquencyModel, on_delete=models.CASCADE)
    attribute_name = models.CharField(max_length=100)
    attribute_value = models.CharField(max_length=100)
    def __str__(self):
        return f'Attribute name: {self.attribute_name}, Attribute value: {self.attribute_value}, Delinquency model: {self.delinquency_model}'

src/FirstDjangoProject22/polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404

from .models import DelinquencyModel


# Create your views here.
def index(request):
    all_models = get_list_or_404(DelinquencyModel)
    context = {'all_models_list': all_models}
    return render(request, 'polls/index.html', context)


def getModelDetails(request):
    model_detail = get_object_or_404(DelinquencyModel, pk=request.POST['model'])
    return render(request, 'polls/detail.html', {'model_detail': model_detail})

def getTrainingResult(request, model_detail_id):
    model_detail = get_object_or_404(DelinquencyModel, pk=model_detail_id)
    print(model_detail)
    for attr in model_detail.modelattributes_set.all():
        print(attr)
    result = request.POST['xxx'] + request.POST['xxy']
    return HttpResponse("Training is done successfully"+result)

src/FirstDjangoProject22/polls/templates/polls/detail.html
<html>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>
    $(function () {
      $("#editxxx").click(function () {
          $('#xxx').removeAttr("readonly");
      });
      $("#editxxy").click(function () {
          $('#xxy').removeAttr("readonly");
      });
  })

</script>
<body>
<h3>{{ model_detail.model_name }}</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:trainingResult' model_detail.id %}" method="post">
    {% csrf_token %}
    <label>Algorithm used: {{ model_detail.algorithm_used }}</label>
    <label>Attributes</label>
    <div>
        <label>name: xxx</label>
        <input type="text" name="xxx" id="xxx" value="xxx" readonly>
        <input type="button" id="editxxx" value="edit">
        <label>name: xxy</label>
        <input type="text" name="xxy" id="xxy" value="xxy" readonly>
        <input type="button" id="editxxy" value="edit">
    </div>
    <input type="text" required id="trainingName" placeholder="Give a name to this training">
    <input type="submit" value="Start Training" id="submitButton">
</form>
</body>
</html>

src/FirstDjangoProject22/polls/templates/polls/index.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if all_models_list %}
<form action="{% url 'polls:detail' %}" method="post">
    {% csrf_token %}
    {% for model in all_models_list %}
    <input type="radio" name="model" value="{{ model.id }}" id="model{{ forloop.counter }}">
    <label for="model{{ forloop.counter }}">{{ model.model_name }}</label>
    {% endfor %}
    <input type="submit" value="Submit">
</form>

{% endif %}
</body>
</html>